'use client'
import { Canvas, useFrame } from "@react-three/fiber";
import React, { useRef, useState } from "react";

function Icosahedron({ radius = 3, detail = 0, speed = 0.7, ...props }) {
  // This reference will give us direct access to the mesh
  const meshRef = useRef();
  // Set up state for the hovered and active state
  const [hovered, setHover] = useState(false);
  // Subscribe this component to the render-loop, rotate the mesh every frame
  useFrame((state, delta) => (meshRef.current.rotation.x += delta * speed));
  // Return view, these are regular three.js elements expressed in JSX
  return (
    <mesh
      {...props}
      ref={meshRef}
      onPointerOver={(event) => setHover(true)}
      onPointerOut={(event) => setHover(false)}
    >
      <icosahedronGeometry args={[radius, detail]} />
      <meshPhysicalMaterial
        color={hovered ? "hotpink" : "hotpink"}
        reflectivity={0.8}
        iridescence={0.427}
      />
    </mesh>
  );
}

export default function FeatureSection() {
  return (
    <section id="feature" className="py-14 px-[126px] relative">
      <Canvas style={{ position: 'absolute', width: 'min(550px, 65%)', bottom: 60, height: 300, zIndex: 1 }}>
        <ambientLight intensity={Math.PI / 5} />
        <spotLight
          position={[-7, 0, 12]}
          angle={0.35}
          penumbra={1}
          decay={0}
          intensity={1.2}
        />
        <camera aspect={16 / 10} />
        <pointLight position={[-10, -10, -10]} decay={0} intensity={Math.PI} />
        <Icosahedron
          position={[-1.5, -1, -1]}
          rotation={[0, 3, 3.2]}
          radius={4}
        />
        <Icosahedron
          position={[2, -1.5, 2]}
          rotation={[0, -3.2, 3]}
          scale={0.5}
          speed={1.2}
        />
      </Canvas>
      <h1 className="font-display text-[32px] leading-[40px] text-center text-white">Features of PowerPlay</h1>
      <div className="grid-cols-2 grid py-11 px-20 gap-[60px] mt-14 bg-ruby rounded-3xl z-10 relative" >
        <div id="first-col">
          <div className="">
            <h2 className="text-dark-kiss text-sm font-semibold">Key features</h2>
            <h1 className="text-white my-5 text-[32px] leading-[40px] font-bold">AI generated NFT - SocialFi
            </h1>
            <p className="text-white/[0.6] font-medium">AI-Generated NFT Profiles: Create unique NFT profile pictures generated by AI based on keywords.
              Community Leaderboard: View and compete on the community leaderboard to see top players and their achievements.
              Profile Exploration: Explore other players&apos; profiles, recent activities, and ENS.</p>
          </div>
        </div>
        <div id="second-col" className="flex flex-col gap-5">
          <div className="border-t border-b border-[#E504983D] p-5 flex flex-col gap-3 inner-purple-shadow rounded-xl">
            <h2 className="text-dark-kiss text-sm font-semibold">GameFi</h2>
            <p className="text-white">European Roulette: Enjoy a fully functional European roulette game with various betting options such as straight, split, street, corner, six line, column, dozen, red, black, high, low, even, and odd.
              Chainlink-Powered Fairness: Powered by Chainlink VRF for random number generation, ensuring fair and transparent gameplay.
              Automated Winnings: Chainlink Automation calculates and transfers winnings to users&apos; wallets automatically after each game.</p>
          </div>
          <div className="border-t border-b border-[#E504983D] p-5 flex flex-col gap-3 inner-purple-shadow rounded-xl">
            <h2 className="text-dark-kiss text-sm font-semibold">DeFi</h2>
            <p className="text-white">Cross-Chain Lending: Deposit tokens on any supported chain as collateral to borrow LINK, facilitating gameplay without needing to sell existing holdings.
              Real-Time Asset Prices: Chainlink Data Feeds provide real-time asset prices for accurate borrowing and lending calculations.
              Seamless Integration: Leveraging Chainlink CCIP for smooth cross-chain asset transfers and communication.</p>
          </div>
          <div className="border-t border-b border-[#E504983D] p-5 flex flex-col gap-3 inner-purple-shadow rounded-xl">
            <h2 className="text-dark-kiss text-sm font-semibold">Additional Features</h2>
            <p className="text-white">Secure and Transparent: Built on top of multiple blockchain technologies ensuring a safe and fraud-free environment.
              Gas-Efficient Transactions: Optimized for low gas fees and high transaction speeds using networks like Polygon, Avalanche, and more.
              Future Expansion: Plans to introduce new games, enhanced AI capabilities, gasless transactions, and Unreal Engine graphics.</p>
          </div>
        </div>
      </div>
    </section>
  )
}